### ISSUE TITLE
I want to use it without "@vue/app"

### ISSUE THREAD

**Issue by Jae-kwang** [eCollect/vue-swipe-actions#18]
I have seen the following error message:
```
Error: Couldn't find preset "@vue/app" relative to directory ...
```

I do not want to use "@vue/app" in presets, is there any other way?

**Comment by nanov** [comment]
When exactly are you getting this message?

**Comment by Jae-kwang** [comment]
Occurs when i import 'vue-swipe-actions'.

I just typed like below, like this:
``` javascript
import { SwipeList, SwipeOut } from 'vue-swipe-actions';

export default {
  components: {
    SwipeOut,
    SwipeList
  }
};
```

**Comment by nanov** [comment]
Thank you for your explanation, i will dive into this now. I wanted to implement new build system anyways. Will keep you updated.

**Comment by Jae-kwang** [comment]
Thank you very much! :)
I look forward to it.

**Comment by nanov** [comment]
I've just released v2.0.0-beta.9 which is built using a brand new rollup build system, could you tell me if it resolves your issue?

**Comment by nanov** [comment]
Some issues cleared with beta.10 release, waiting for your feedback.

**Comment by Jae-kwang** [comment]
Thank you for your work :)
However, an same error still occurs.
```
ERROR in ./node_modules/vue-swipe-actions/src/index.esm.js
Module build failed: Error: Couldn't find preset "@vue/app" relative to directory "/Users/jei/myProject/node_modules/vue-swipe-actions"
    at /Users/jei/myProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)'
```

**Comment by nanov** [comment]
Could you provide a repository for me to test?

**Comment by nanov** [comment]
I think I know why this happens, may I guess that you have no babel setup in your project?
Could you try to see whats the message with beta.11?

**Comment by Jae-kwang** [comment]
my project has babel setup like this
```
{
  "presets": [["es2015", { "modules": false }], "stage-0"],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

**Comment by Jae-kwang** [comment]
I applied for beta.11 then occurs error below
```
ERROR in ./node_modules/vue-swipe-actions/src/components/SwipeList.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
| 	<div
| 		class="swipeout-list"
 @ ./node_modules/vue-swipe-actions/src/components/index.js 12:17-43
 @ ./node_modules/vue-swipe-actions/src/index.esm.js
```

**Comment by Jae-kwang** [comment]
I will provide a part of my project.
https://github.com/Jae-kwang/myProject

**Comment by nanov** [comment]
Thank you for the repository.

I will investigate and try to find a solution that works!

**Comment by nanov** [comment]
Well, in your case, it seems that removing the [following line](https://github.com/Jae-kwang/myProject/blob/77c8bc50cc87ff6cf2f18a8395a7901381318199/build/webpack.config.js#L26) solves the problem, as this release is aimed to be built with your native config.

**Comment by Jae-kwang** [comment]
Thank you very much! I did not consider this part.
You have been a great help to me. :)

**Comment by nanov** [comment]
As a side note, once i find the time, i will rewrite the SwipeList component as a js one ( not using .vue extensions ) and this problem wont persist.
